@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ofek2608.emc_interface;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;